-- Migration 010: agent_drafts + agent_sessions
-- Target project: hsnpveroqzmhppfsfaua (Agent DB, NOT boston-ar)
-- Authorization model: no RLS (service_role only from Next.js API routes).
-- The web UI authenticates users against boston-ar Supabase, validates role in
-- ('admin','autor'), and filters by author_id server-side.
-- author_id is the UUID from boston-ar auth.users (no FK, different project).
-- published_post_id references posts.id in boston-ar (no FK, different project).

CREATE TABLE IF NOT EXISTS public.agent_drafts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  author_id UUID NOT NULL,
  title TEXT NOT NULL,
  slug TEXT,
  excerpt TEXT,
  html_content TEXT,
  category TEXT NOT NULL,
  access_level TEXT DEFAULT '000',
  source_file_name TEXT,
  source_file_type TEXT,
  agent_session_id TEXT,
  chat_history JSONB DEFAULT '[]'::jsonb,
  status TEXT DEFAULT 'pending_review',
  error_message TEXT,
  published_post_id UUID,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT agent_drafts_status_check CHECK (status IN ('pending_review','approved','rejected','published','error')),
  CONSTRAINT agent_drafts_source_type_check CHECK (source_file_type IS NULL OR source_file_type IN ('pdf','csv')),
  CONSTRAINT agent_drafts_access_level_check CHECK (access_level IN ('000','001','002'))
);

CREATE INDEX IF NOT EXISTS idx_agent_drafts_author_id ON public.agent_drafts(author_id);
CREATE INDEX IF NOT EXISTS idx_agent_drafts_status ON public.agent_drafts(status);
CREATE INDEX IF NOT EXISTS idx_agent_drafts_created_at ON public.agent_drafts(created_at DESC);

CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS agent_drafts_set_updated_at ON public.agent_drafts;
CREATE TRIGGER agent_drafts_set_updated_at
  BEFORE UPDATE ON public.agent_drafts
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Optional second table: persisted agent sessions (in case we want to survive
-- server restarts or share sessions across replicas later).
CREATE TABLE IF NOT EXISTS public.agent_sessions (
  id TEXT PRIMARY KEY,
  draft_id UUID REFERENCES public.agent_drafts(id) ON DELETE CASCADE,
  author_id UUID NOT NULL,
  state JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_sessions_draft_id ON public.agent_sessions(draft_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_author_id ON public.agent_sessions(author_id);

DROP TRIGGER IF EXISTS agent_sessions_set_updated_at ON public.agent_sessions;
CREATE TRIGGER agent_sessions_set_updated_at
  BEFORE UPDATE ON public.agent_sessions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

COMMENT ON TABLE public.agent_drafts IS 'Staging of reports generated by the Claude analyst agent. Validated by autor/admin before publishing to boston-ar posts.';
COMMENT ON TABLE public.agent_sessions IS 'Persisted agent chat sessions, keyed by the session_id returned from /analyze.';
